filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        remove_extra_empty_lines: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: true
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: true
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
                always: true
                else_on_new_line: false
            for:
                opening: undefined
                always: true
            while:
                opening: undefined
                always: true
            do_while:
                opening: undefined
                always: true
                while_on_new_line: false
            switch:
                opening: undefined
            try:
                opening: undefined
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build:
    environment:
        php:
            version: '7.1'
        java: java-8-oracle
        postgresql: false
        mongodb: false
        mysql: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false

    dependencies:
        before:
            - sudo apt-get install -y software-properties-common
            - sudo add-apt-repository ppa:ondrej/php -y
            - sudo apt-get update
            - sudo apt-get install -y ntp
            - sudo apt-get install -y libstdc++6 build-essential curl cmake g++ libpcre3-dev libssl-dev make openssl openjdk-8-jre python-dev python-setuptools libgmp-dev
            - cd /tmp && wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.28.0/libuv1_1.28.0-1_amd64.deb && wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.28.0/libuv1-dev_1.28.0-1_amd64.deb
            - sudo dpkg -i libuv1_1.28.0-1_amd64.deb
            - sudo dpkg -i libuv1-dev_1.28.0-1_amd64.deb
            - cd /tmp && wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.12.0/cassandra-cpp-driver_2.12.0-1_amd64.deb && wget http://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.12.0/cassandra-cpp-driver-dev_2.12.0-1_amd64.deb
            - sudo dpkg -i cassandra-cpp-driver_2.12.0-1_amd64.deb
            - sudo dpkg -i cassandra-cpp-driver-dev_2.12.0-1_amd64.deb
            - sudo apt-get clean
            - sudo apt-get update
            - sudo apt-get install dpkg
            - sudo rm -rf /var/lib/cassandra/* /etc/init.d/cassandra /etc/security/limits.d/cassandra.conf
            - echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
            - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
            - sudo apt-get update && sudo apt-get install -y cassandra && service cassandra start && pip install cqlsh && sleep 3s && /usr/bin/cqlsh -f /home/scrutinizer/build/setup_cassandra_unittest_keyspace.cql

        override:
            - yes | pecl install cassandra
            - cd /home/scrutinizer/build/ && composer install --no-interaction
        
    cache:
        directories:
            - ~/.cache/pip
    tests:
        override:
            - command: 'vendor/bin/phpunit --coverage-clover build/logs/clover.xml'
              coverage:
                  file: 'build/logs/clover.xml'
                  format: 'clover'