language: php
dist: xenial
php:
  - 7.1

sudo: required

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - build-essential 
      - curl
      - cmake
      - g++
      - libpcre3-dev
      - libssl-dev
      - make
      - openssl
      - openjdk-8-jre
      - python-dev
      - python-setuptools
      - libgmp-dev

install:
  - bash travis_bootstrap.sh
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'php vendor/bin/coveralls -v'

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log    
