version: '3'

services:

  scylloquent-1:
    image: scylladb/scylla
    container_name: scylloquent-1
    command: --smp 1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    ports:
      - "9042:9042"
    expose:
      - "7199"

  scylloquent-2:
    image: scylladb/scylla
    container_name: scylloquent-2
    command: --smp 1 --seeds=scylloquent-1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    expose:
      - "7199"

  scylloquent-3:
    image: scylladb/scylla
    container_name: scylloquent-3
    command: --smp 1 --seeds=scylloquent-1
    environment:
      - "SCYLLA_JMX_ADDR=-ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=-r"
    expose:
      - "7199"
